FROM quay.io/jupyter/base-notebook:latest
RUN conda create -n jupyterlab-ext --override-channels --strict-channel-priority -c conda-forge -c nodefaults jupyterlab=4 nodejs=18 git copier=7 jinja2-time -y
RUN conda run -n jupyterlab-ext
USER root
COPY . /extension
WORKDIR /extension
RUN pip install -ve .
CMD ["jupyterhub-singleuser","--LabApp.collaborative=True"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              