name: collab-learning-extension-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.10,<3.11.0a0
  - jupyterlab >=4.0.0,<5
  # labextension build dependencies
  - nodejs >=18,<19
  - pip
  - wheel
  - jupyter-collaboration 