#!/usr/bin/env bash
set -eux

python -m pip install -e . --ignore-installed --no-deps -vv

jupyter labextension disable jupyter-offlinenotebook || echo "not enabled"
python -m pip uninstall -y jupyter-offlinenotebook || echo "not installed"

jupyter labextension disable jupyter-resource-usage || echo "not enabled"
python -m pip uninstall -y jupyter-resource-usage || echo "not installed"

# list all extensions
jupyter server extension list
jupyter labextension list

# server configuration
cp binder/jupyter_config.json .
